### PR TITLE
pep8 -> pycodestyle

### PR DESCRIPTION
**Pull request by c-martinez**

### CODE REVIEW

**Comment by c-martinez** [comment]
Also, should `positive_limits.py` script be provided?

**Comment by orchid00** [comment]
Thank you @c-martinez 

If you want an R example this is a source https://cran.r-project.org/web/packages/styler/index.html

**Comment by c-martinez** [comment]
Hi @orchid00,

Thanks for the link. Although my question was in a slightly different direction: the challenge mentions a `positive_limits.py` script, on which you should run `pycodestyle` -- but the script is not in the repo. Should this script be on the repo? Otherwise, where can it be found?

**Comment by orchid00** [comment]
hi @c-martinez 

 I wasn't sure where that script is, but it is right where it should be! https://github.com/SoftDev4Research/4OSS-lesson/tree/gh-pages/code
can you add a link to it? or add a comment to assign someone from that episode to add the link.
Thanks!

**Comment by c-martinez** [comment]
PR #59 sent.

**Pull request merged**
